/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as FranquiciasIndexRouteImport } from './routes/franquicias.index'
import { Route as FranquiciasIdRouteImport } from './routes/franquicias.$id'
import { Route as NegociosIndexRouteImport } from './routes/negocios.index'
import { Route as NegociosIdRouteImport } from './routes/negocios.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const FranquiciasIndexRoute = FranquiciasIndexRouteImport.update({
  id: '/franquicias/',
  path: '/franquicias/',
  getParentRoute: () => rootRouteImport,
} as any)
const FranquiciasIdRoute = FranquiciasIdRouteImport.update({
  id: '/franquicias/$id',
  path: '/franquicias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosIndexRoute = NegociosIndexRouteImport.update({
  id: '/negocios/',
  path: '/negocios/',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosIdRoute = NegociosIdRouteImport.update({
  id: '/negocios/$id',
  path: '/negocios/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracion': typeof ConfiguracionRoute
  '/perfil': typeof PerfilRoute
  '/franquicias/$id': typeof FranquiciasIdRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/franquicias/': typeof FranquiciasIndexRoute
  '/negocios/': typeof NegociosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracion': typeof ConfiguracionRoute
  '/perfil': typeof PerfilRoute
  '/franquicias/$id': typeof FranquiciasIdRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/franquicias': typeof FranquiciasIndexRoute
  '/negocios': typeof NegociosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracion': typeof ConfiguracionRoute
  '/perfil': typeof PerfilRoute
  '/franquicias/$id': typeof FranquiciasIdRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/franquicias/': typeof FranquiciasIndexRoute
  '/negocios/': typeof NegociosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/catalogo'
    | '/configuracion'
    | '/perfil'
    | '/franquicias/$id'
    | '/negocios/$id'
    | '/franquicias/'
    | '/negocios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/catalogo'
    | '/configuracion'
    | '/perfil'
    | '/franquicias/$id'
    | '/negocios/$id'
    | '/franquicias'
    | '/negocios'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/catalogo'
    | '/configuracion'
    | '/perfil'
    | '/franquicias/$id'
    | '/negocios/$id'
    | '/franquicias/'
    | '/negocios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  CatalogoRoute: typeof CatalogoRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  PerfilRoute: typeof PerfilRoute
  FranquiciasIdRoute: typeof FranquiciasIdRoute
  NegociosIdRoute: typeof NegociosIdRoute
  FranquiciasIndexRoute: typeof FranquiciasIndexRoute
  NegociosIndexRoute: typeof NegociosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franquicias/': {
      id: '/franquicias/'
      path: '/franquicias'
      fullPath: '/franquicias/'
      preLoaderRoute: typeof FranquiciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franquicias/$id': {
      id: '/franquicias/$id'
      path: '/franquicias/$id'
      fullPath: '/franquicias/$id'
      preLoaderRoute: typeof FranquiciasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios/': {
      id: '/negocios/'
      path: '/negocios'
      fullPath: '/negocios/'
      preLoaderRoute: typeof NegociosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios/$id': {
      id: '/negocios/$id'
      path: '/negocios/$id'
      fullPath: '/negocios/$id'
      preLoaderRoute: typeof NegociosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  CatalogoRoute: CatalogoRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  PerfilRoute: PerfilRoute,
  FranquiciasIdRoute: FranquiciasIdRoute,
  NegociosIdRoute: NegociosIdRoute,
  FranquiciasIndexRoute: FranquiciasIndexRoute,
  NegociosIndexRoute: NegociosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
