/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NegociosIndexRouteImport } from './routes/negocios.index'
import { Route as NegociosIdRouteImport } from './routes/negocios.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosIndexRoute = NegociosIndexRouteImport.update({
  id: '/negocios/',
  path: '/negocios/',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosIdRoute = NegociosIdRouteImport.update({
  id: '/negocios/$id',
  path: '/negocios/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/negocios/': typeof NegociosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/negocios': typeof NegociosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/negocios/$id': typeof NegociosIdRoute
  '/negocios/': typeof NegociosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/negocios/$id' | '/negocios/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/negocios/$id' | '/negocios'
  id: '__root__' | '/' | '/negocios/$id' | '/negocios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NegociosIdRoute: typeof NegociosIdRoute
  NegociosIndexRoute: typeof NegociosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios/': {
      id: '/negocios/'
      path: '/negocios'
      fullPath: '/negocios/'
      preLoaderRoute: typeof NegociosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios/$id': {
      id: '/negocios/$id'
      path: '/negocios/$id'
      fullPath: '/negocios/$id'
      preLoaderRoute: typeof NegociosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NegociosIdRoute: NegociosIdRoute,
  NegociosIndexRoute: NegociosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
